baseURL = 'https://rhew.org/projects/'
languageCode = 'en-us'
title = 'rhew.org: projects'
theme = ["hugo-video", "rhew-org-theme"]

[params]
  centerTheme = true
[languages]
  [languages.en]
    title = "rhew.org: projects"
    [languages.en.params]
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"
    [languages.en.params.logo]
      logoText = "rhew.org:~/projects$"
    [languages.en.menu]
      [[languages.en.menu.main]]
        url = "/tags/recipes/"
        name = "recipes"
        weight = 1
        identifier = "recipes"
      [[languages.en.menu.main]]
        url = "/tags/supervillainy/"
        name = "supervillainy"
        weight = 2
        identifier = "supervillainy"
      [[languages.en.menu.main]]
        url = "/tags/"
        name = "and other shenanigans"
        weight = 3
        identifier = "shenanigans"
