baseURL = 'https://rhew.org/projects/'
languageCode = 'en-us'
title = 'rhew.org: projects'
theme = 'rhew-org-theme'

[languages]
  [languages.en]
    title = "rhew.org: projects"
    [languages.en.params]
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"
    [languages.en.params.logo]
      logoText = "rhew.org:~/projects$"
